"""
app.py  —  FastAPI web service for the Algebra 2 Radical Test Generator
==========================================================================

Start the server
----------------
    uvicorn app:app --reload               # development  (http://127.0.0.1:8000)
    uvicorn app:app --host 0.0.0.0 --port 8000   # production / Docker

Interactive API docs  (auto-generated by FastAPI)
-------------------------------------------------
    http://127.0.0.1:8000/docs      Swagger UI
    http://127.0.0.1:8000/redoc     ReDoc

Endpoints
---------
    GET  /                    Built-in HTML form / quick test UI
    GET  /api/health          Health check
    GET  /api/sections        Section metadata (titles, bounds, defaults)
    POST /api/generate/txt    Download TXT worksheet
    POST /api/generate/pdf    Download PDF worksheet
    POST /api/generate/zip    Download ZIP containing both TXT and PDF
    POST /api/generate/info   JSON preview (no file, just metadata + question count)

Author : zekeg
Created: 12/02/2026
"""

import io
import zipfile
from typing import Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse
from pydantic import BaseModel, Field, field_validator, model_validator

import algebra2_radical_test as core


# ═══════════════════════════════════════════════════════════════
#  App instance
# ═══════════════════════════════════════════════════════════════

app = FastAPI(
    title="Algebra 2 Radical Test Generator",
    description=(
        "Generate randomized Algebra 2 worksheets covering radical simplification. "
        "Download as print-ready PDF or as TXT for Google Docs / Auto-LaTeX rendering."
    ),
    version="2.0.0",
    contact={"name": "zekeg"},
    license_info={"name": "Copyright (c) zekeg 2026"},
)

# Allow all origins in development; tighten for production
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ═══════════════════════════════════════════════════════════════
#  Pydantic request / response models
# ═══════════════════════════════════════════════════════════════

class SectionConfig(BaseModel):
    """Per-section question count override. Keys are section numbers 1–3."""
    section_1: Optional[int] = Field(
        default=None, ge=1, le=30,
        description="Number of questions for Section 1 (Divide & Simplify). "
                    "Omit to use the default (8).",
        examples=[8],
    )
    section_2: Optional[int] = Field(
        default=None, ge=1, le=20,
        description="Number of questions for Section 2 (Powers / Exponents). "
                    "Omit to use the default (4).",
        examples=[4],
    )
    section_3: Optional[int] = Field(
        default=None, ge=1, le=20,
        description="Number of questions for Section 3 (Multiply Radicals). "
                    "Omit to use the default (3).",
        examples=[3],
    )


class GenerateRequest(BaseModel):
    """
    Parameters for worksheet generation.
    All fields have sensible defaults so you can POST `{}` for a quick test.
    """
    test_title: str = Field(
        default="Algebra 2 Test: Simplifying Radicals",
        min_length=1,
        max_length=120,
        description="Title printed at the top of every version.",
        examples=["Period 3 — Radicals Quiz"],
    )
    num_versions: int = Field(
        default=5,
        ge=1,
        le=100,
        description="Number of unique randomized versions to generate.",
        examples=[33],
    )
    sections: List[int] = Field(
        default=[1, 2, 3],
        description="Which sections to include. Any non-empty subset of [1, 2, 3].",
        examples=[[1, 2, 3]],
    )
    section_counts: Optional[SectionConfig] = Field(
        default=None,
        description=(
            "Override the number of questions per section. "
            "Omit a section key to use its default."
        ),
    )
    var_min: int = Field(
        default=1, ge=1, le=20,
        description="Minimum variable exponent (e.g. x^n — controls n).",
        examples=[1],
    )
    var_max: int = Field(
        default=10, ge=1, le=20,
        description="Maximum variable exponent.",
        examples=[10],
    )
    root_min: int = Field(
        default=2, ge=2, le=10,
        description="Minimum radical index (2=sqrt, 3=cbrt, 4=4th-root, …).",
        examples=[2],
    )
    root_max: int = Field(
        default=3, ge=2, le=10,
        description="Maximum radical index. Each problem draws randomly from [root_min, root_max].",
        examples=[3],
    )
    name_label: str = Field(
        default="Name",
        max_length=30,
        description="Label for the student name field.",
        examples=["Nombre"],
    )
    date_label: str = Field(
        default="Date",
        max_length=30,
        description="Label for the date field.",
        examples=["Fecha"],
    )
    period_label: str = Field(
        default="Period",
        max_length=30,
        description="Label for the period field.",
        examples=["Periodo"],
    )

    # ── Validators ────────────────────────────────────────────

    @field_validator("sections")
    @classmethod
    def validate_sections(cls, v):
        valid = {1, 2, 3}
        bad   = [s for s in v if s not in valid]
        if bad:
            raise ValueError(f"Invalid section number(s): {bad}. Must be 1, 2, or 3.")
        if not v:
            raise ValueError("At least one section must be selected.")
        return sorted(set(v))   # deduplicate and sort

    @model_validator(mode="after")
    def validate_ranges(self):
        if self.var_min > self.var_max:
            raise ValueError("var_min must be <= var_max")
        if self.root_min > self.root_max:
            raise ValueError("root_min must be <= root_max")
        return self

    # ── Helper: convert SectionConfig -> Dict[int, int] ──────

    def resolved_section_counts(self) -> Dict[int, int]:
        """Return {sec_num: count} using defaults for any omitted section."""
        defaults = core.SECTION_Q_DEFAULTS
        if self.section_counts is None:
            return {s: defaults[s] for s in self.sections}
        mapping = {
            1: self.section_counts.section_1,
            2: self.section_counts.section_2,
            3: self.section_counts.section_3,
        }
        return {s: (mapping[s] if mapping[s] is not None else defaults[s])
                for s in self.sections}


class SectionMeta(BaseModel):
    section: int
    title: str
    description: str
    default_questions: int
    min_questions: int
    max_questions: int


class SectionsResponse(BaseModel):
    sections: List[SectionMeta]


class InfoResponse(BaseModel):
    test_title: str
    num_versions: int
    sections: List[int]
    section_counts: Dict[str, int]
    total_questions_per_version: int
    var_min: int
    var_max: int
    root_min: int
    root_max: int
    name_label: str
    date_label: str
    period_label: str
    txt_size_estimate_kb: float
    note: str


# ═══════════════════════════════════════════════════════════════
#  Shared generation helper
# ═══════════════════════════════════════════════════════════════

def _build_kwargs(req: GenerateRequest) -> dict:
    return dict(
        num_versions   = req.num_versions,
        test_title     = req.test_title,
        sections       = req.sections,
        section_counts = req.resolved_section_counts(),
        var_min        = req.var_min,
        var_max        = req.var_max,
        root_min       = req.root_min,
        root_max       = req.root_max,
        name_label     = req.name_label,
        date_label     = req.date_label,
        period_label   = req.period_label,
    )


def _safe_filename(title: str) -> str:
    """Strip characters that are unsafe in Content-Disposition headers."""
    return (title.replace(" ", "_")
                 .replace(":", "")
                 .replace("/", "-")
                 .replace("\\", "-")[:60])


# ═══════════════════════════════════════════════════════════════
#  Routes
# ═══════════════════════════════════════════════════════════════

# ── Health ────────────────────────────────────────────────────

@app.get(
    "/api/health",
    tags=["System"],
    summary="Health check",
    response_description="Service status",
)
def health():
    """Returns `{\"status\": \"ok\"}` when the service is running."""
    return {"status": "ok", "service": "Algebra 2 Radical Test Generator"}


# ── Section metadata ──────────────────────────────────────────

@app.get(
    "/api/sections",
    tags=["Metadata"],
    response_model=SectionsResponse,
    summary="List available sections",
    response_description="Metadata for all three worksheet sections",
)
def get_sections():
    """
    Returns title, description, default question count, and min/max bounds
    for each of the three worksheet sections.
    """
    items = []
    for s in [1, 2, 3]:
        lo, hi = core.SECTION_Q_BOUNDS[s]
        items.append(SectionMeta(
            section           = s,
            title             = core.SECTION_TITLES[s],
            description       = core.SECTION_DESCRIPTIONS[s],
            default_questions = core.SECTION_Q_DEFAULTS[s],
            min_questions     = lo,
            max_questions     = hi,
        ))
    return SectionsResponse(sections=items)


# ── Info / dry-run ────────────────────────────────────────────

@app.post(
    "/api/generate/info",
    tags=["Generate"],
    response_model=InfoResponse,
    summary="Preview generation parameters (no file produced)",
    response_description="Summary of what would be generated",
)
def generate_info(req: GenerateRequest):
    """
    Validates the request and returns a JSON summary of what would be generated —
    useful for confirming settings before requesting a full TXT/PDF download.
    No worksheet is actually produced.
    """
    counts = req.resolved_section_counts()
    total  = sum(counts.values())
    # Very rough TXT size estimate: ~300 chars per question * versions
    est_kb = round(total * req.num_versions * 300 / 1024, 1)

    return InfoResponse(
        test_title                    = req.test_title,
        num_versions                  = req.num_versions,
        sections                      = req.sections,
        section_counts                = {str(k): v for k, v in counts.items()},
        total_questions_per_version   = total,
        var_min                       = req.var_min,
        var_max                       = req.var_max,
        root_min                      = req.root_min,
        root_max                      = req.root_max,
        name_label                    = req.name_label,
        date_label                    = req.date_label,
        period_label                  = req.period_label,
        txt_size_estimate_kb          = est_kb,
        note = (
            "POST to /api/generate/txt or /api/generate/pdf to download the worksheet. "
            "PDF generation is slower due to math image rendering."
        ),
    )


# ── TXT download ──────────────────────────────────────────────

@app.post(
    "/api/generate/txt",
    tags=["Generate"],
    summary="Generate and download worksheet as TXT",
    response_description="UTF-8 text file with $$ ... $$ LaTeX blocks",
    responses={200: {"content": {"text/plain": {}}}},
)
def generate_txt(req: GenerateRequest):
    """
    Generate the worksheet as a plain-text file.

    All math expressions are wrapped in `$$ ... $$`.
    To render them:

    1. Copy the file contents into a Google Doc.
    2. **Extensions → Add-ons → Auto-LaTeX Equations → Start**
    """
    try:
        txt_bytes = core.build_txt_bytes(**_build_kwargs(req))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    fname = f"{_safe_filename(req.test_title)}_v{req.num_versions}.txt"
    return StreamingResponse(
        io.BytesIO(txt_bytes),
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


# ── PDF download ──────────────────────────────────────────────

@app.post(
    "/api/generate/pdf",
    tags=["Generate"],
    summary="Generate and download worksheet as PDF",
    response_description="Print-ready PDF with rendered math images",
    responses={200: {"content": {"application/pdf": {}}}},
)
def generate_pdf(req: GenerateRequest):
    """
    Generate the worksheet as a print-ready PDF.

    All math expressions are rendered as crisp images using matplotlib's
    mathtext engine — **no LaTeX installation required on the server**.

    ⚠️ This endpoint is slower than `/api/generate/txt` because each
    mathematical expression is individually rendered as a PNG image.
    For 33 versions with default settings, expect 15–60 seconds.
    """
    try:
        pdf_bytes = core.build_pdf_bytes(**_build_kwargs(req))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    fname = f"{_safe_filename(req.test_title)}_v{req.num_versions}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


# ── ZIP download (TXT + PDF) ──────────────────────────────────

@app.post(
    "/api/generate/zip",
    tags=["Generate"],
    summary="Generate and download both TXT and PDF in a ZIP archive",
    response_description="ZIP file containing the TXT and PDF worksheets",
    responses={200: {"content": {"application/zip": {}}}},
)
def generate_zip(req: GenerateRequest):
    """
    Generate both formats and bundle them in a single ZIP archive.

    The ZIP contains:
    - `<title>_v<N>.txt`  — Google Docs / Auto-LaTeX version
    - `<title>_v<N>.pdf`  — print-ready PDF version
    """
    kwargs = _build_kwargs(req)
    base   = f"{_safe_filename(req.test_title)}_v{req.num_versions}"

    try:
        txt_bytes = core.build_txt_bytes(**kwargs)
        pdf_bytes = core.build_pdf_bytes(**kwargs)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{base}.txt", txt_bytes)
        zf.writestr(f"{base}.pdf", pdf_bytes)
    zip_buf.seek(0)

    return StreamingResponse(
        zip_buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{base}.zip"'},
    )


# ═══════════════════════════════════════════════════════════════
#  Built-in HTML test UI  (served at /)
# ═══════════════════════════════════════════════════════════════

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
def root():
    return """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Algebra 2 Radical Test Generator</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:system-ui,sans-serif;background:#f0f4f8;color:#1a202c;min-height:100vh}
    header{background:#2b6cb0;color:#fff;padding:1.5rem 2rem}
    header h1{font-size:1.5rem;font-weight:700}
    header p{font-size:.9rem;opacity:.85;margin-top:.3rem}
    main{max-width:860px;margin:2rem auto;padding:0 1rem}
    .card{background:#fff;border-radius:.75rem;padding:1.75rem;margin-bottom:1.5rem;
          box-shadow:0 1px 3px rgba(0,0,0,.1)}
    h2{font-size:1.1rem;font-weight:700;color:#2b6cb0;margin-bottom:1rem;
       border-bottom:2px solid #ebf4ff;padding-bottom:.5rem}
    label{display:block;font-size:.85rem;font-weight:600;color:#4a5568;margin-bottom:.25rem;margin-top:.9rem}
    input,select{width:100%;padding:.5rem .7rem;border:1px solid #cbd5e0;border-radius:.4rem;
                 font-size:.95rem;background:#fff;color:#1a202c}
    input:focus,select:focus{outline:2px solid #4299e1;border-color:#4299e1}
    .row{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
    .row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1rem}
    .sec-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:1rem;margin-top:.5rem}
    .sec-card{border:1px solid #e2e8f0;border-radius:.5rem;padding:1rem}
    .sec-card input[type=checkbox]{width:auto;margin-right:.4rem}
    .sec-title{font-weight:700;font-size:.9rem;margin-bottom:.5rem}
    .btns{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:1.25rem}
    button{padding:.65rem 1.5rem;border:none;border-radius:.5rem;font-size:.95rem;
           font-weight:700;cursor:pointer;transition:opacity .15s}
    .btn-txt{background:#2b6cb0;color:#fff} .btn-pdf{background:#2f855a;color:#fff}
    .btn-zip{background:#744210;color:#fff} .btn-info{background:#553c9a;color:#fff}
    button:hover{opacity:.88} button:disabled{opacity:.5;cursor:not-allowed}
    #status{margin-top:1rem;padding:.75rem 1rem;border-radius:.4rem;font-size:.9rem;display:none}
    .info-bg{background:#ebf4ff;border:1px solid #90cdf4;color:#1a365d}
    .ok-bg{background:#f0fff4;border:1px solid #9ae6b4;color:#1c4532}
    .err-bg{background:#fff5f5;border:1px solid #feb2b2;color:#742a2a}
    pre{background:#1a202c;color:#e2e8f0;padding:1rem;border-radius:.5rem;
        overflow-x:auto;font-size:.8rem;margin-top:.75rem}
    a.docs-link{color:#2b6cb0;font-weight:600;font-size:.9rem}
    footer{text-align:center;color:#718096;font-size:.8rem;padding:2rem}
  </style>
</head>
<body>
<header>
  <h1>📐 Algebra 2 Radical Test Generator</h1>
  <p>Generate randomized worksheets — download as print-ready PDF or Google Docs TXT</p>
</header>
<main>

  <!-- API links -->
  <div class="card" style="display:flex;gap:1.5rem;align-items:center;flex-wrap:wrap">
    <a class="docs-link" href="/docs" target="_blank">📖 Swagger UI (interactive API docs)</a>
    <a class="docs-link" href="/redoc" target="_blank">📋 ReDoc</a>
    <a class="docs-link" href="/api/sections" target="_blank">🔍 GET /api/sections</a>
    <a class="docs-link" href="/api/health" target="_blank">❤ GET /api/health</a>
  </div>

  <!-- Form -->
  <div class="card">
    <h2>Configure Worksheet</h2>

    <label>Test Title</label>
    <input id="title" type="text" value="Algebra 2 Test: Simplifying Radicals" maxlength="120"/>

    <div class="row" style="margin-top:.9rem">
      <div>
        <label>Number of Versions (1–100)</label>
        <input id="num_versions" type="number" value="5" min="1" max="100"/>
      </div>
      <div></div>
    </div>

    <label>Sections  (check to include; enter question count per section)</label>
    <div class="sec-grid">
      <div class="sec-card">
        <div class="sec-title">
          <input type="checkbox" id="sec1" checked/>
          <label for="sec1" style="display:inline;margin:0">Section 1</label>
        </div>
        <div style="font-size:.8rem;color:#718096;margin-bottom:.5rem">Divide &amp; Simplify</div>
        <label style="margin-top:0">Questions (1–30)</label>
        <input id="cnt1" type="number" value="8" min="1" max="30"/>
      </div>
      <div class="sec-card">
        <div class="sec-title">
          <input type="checkbox" id="sec2" checked/>
          <label for="sec2" style="display:inline;margin:0">Section 2</label>
        </div>
        <div style="font-size:.8rem;color:#718096;margin-bottom:.5rem">Powers / Exponents</div>
        <label style="margin-top:0">Questions (1–20)</label>
        <input id="cnt2" type="number" value="4" min="1" max="20"/>
      </div>
      <div class="sec-card">
        <div class="sec-title">
          <input type="checkbox" id="sec3" checked/>
          <label for="sec3" style="display:inline;margin:0">Section 3</label>
        </div>
        <div style="font-size:.8rem;color:#718096;margin-bottom:.5rem">Multiply Radicals</div>
        <label style="margin-top:0">Questions (1–20)</label>
        <input id="cnt3" type="number" value="3" min="1" max="20"/>
      </div>
    </div>

    <div class="row">
      <div>
        <label>Root Index — Min (2=√  3=∛  …)</label>
        <input id="root_min" type="number" value="2" min="2" max="10"/>
      </div>
      <div>
        <label>Root Index — Max</label>
        <input id="root_max" type="number" value="3" min="2" max="10"/>
      </div>
    </div>

    <div class="row">
      <div>
        <label>Variable Exponent — Min</label>
        <input id="var_min" type="number" value="1" min="1" max="20"/>
      </div>
      <div>
        <label>Variable Exponent — Max</label>
        <input id="var_max" type="number" value="10" min="1" max="20"/>
      </div>
    </div>

    <div class="row3">
      <div>
        <label>Name label</label>
        <input id="name_label" type="text" value="Name" maxlength="30"/>
      </div>
      <div>
        <label>Date label</label>
        <input id="date_label" type="text" value="Date" maxlength="30"/>
      </div>
      <div>
        <label>Period label</label>
        <input id="period_label" type="text" value="Period" maxlength="30"/>
      </div>
    </div>

    <div class="btns">
      <button class="btn-info"  onclick="doInfo()">🔍 Preview (JSON)</button>
      <button class="btn-txt"   onclick="doDownload('txt')">⬇ Download TXT</button>
      <button class="btn-pdf"   onclick="doDownload('pdf')">⬇ Download PDF</button>
      <button class="btn-zip"   onclick="doDownload('zip')">⬇ Download ZIP (both)</button>
    </div>

    <div id="status"></div>
  </div>

  <!-- Info output -->
  <div id="info_card" class="card" style="display:none">
    <h2>Preview Response</h2>
    <pre id="info_pre"></pre>
  </div>

</main>
<footer>Algebra 2 Radical Test Generator &bull; FastAPI + matplotlib + ReportLab</footer>

<script>
function buildPayload(){
  const sections=[], section_counts={};
  [[1,'sec1','cnt1'],[2,'sec2','cnt2'],[3,'sec3','cnt3']].forEach(([n,cb,ci])=>{
    if(document.getElementById(cb).checked){
      sections.push(n);
      const k='section_'+n;
      section_counts[k]=parseInt(document.getElementById(ci).value)||undefined;
    }
  });
  return {
    test_title:    document.getElementById('title').value,
    num_versions:  parseInt(document.getElementById('num_versions').value),
    sections,
    section_counts,
    root_min: parseInt(document.getElementById('root_min').value),
    root_max: parseInt(document.getElementById('root_max').value),
    var_min:  parseInt(document.getElementById('var_min').value),
    var_max:  parseInt(document.getElementById('var_max').value),
    name_label:   document.getElementById('name_label').value,
    date_label:   document.getElementById('date_label').value,
    period_label: document.getElementById('period_label').value,
  };
}

function setStatus(msg, type){
  const el=document.getElementById('status');
  el.className=type+'-bg'; el.textContent=msg; el.style.display='block';
}

async function doInfo(){
  setStatus('Fetching preview…','info');
  try{
    const r=await fetch('/api/generate/info',{
      method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify(buildPayload())
    });
    const j=await r.json();
    if(!r.ok){setStatus('Error: '+(j.detail||r.statusText),'err');return;}
    document.getElementById('info_pre').textContent=JSON.stringify(j,null,2);
    document.getElementById('info_card').style.display='block';
    setStatus('Preview ready.','ok');
  }catch(e){setStatus('Network error: '+e.message,'err');}
}

async function doDownload(fmt){
  const mediaTypes={txt:'text/plain',pdf:'application/pdf',zip:'application/zip'};
  const labels={txt:'TXT','pdf':'PDF','zip':'ZIP'};
  setStatus(`Generating ${labels[fmt]} — please wait…`,'info');
  const allBtns=document.querySelectorAll('button');
  allBtns.forEach(b=>b.disabled=true);
  try{
    const r=await fetch('/api/generate/'+fmt,{
      method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify(buildPayload())
    });
    if(!r.ok){
      const j=await r.json().catch(()=>({detail:r.statusText}));
      setStatus('Error: '+(j.detail||r.statusText),'err');return;
    }
    const blob=await r.blob();
    const cd=r.headers.get('Content-Disposition')||'';
    const m=cd.match(/filename="([^"]+)"/);
    const fname=m?m[1]:`worksheet.${fmt}`;
    const url=URL.createObjectURL(blob);
    const a=document.createElement('a');
    a.href=url; a.download=fname; document.body.appendChild(a);
    a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
    setStatus(`${labels[fmt]} downloaded: ${fname}`,'ok');
  }catch(e){setStatus('Network error: '+e.message,'err');}
  finally{allBtns.forEach(b=>b.disabled=false);}
}
</script>
</body>
</html>"""
