"""
app.py  —  FastAPI web service for the Algebra 2 Radical Test Generator
==========================================================================

Start the server
----------------
    uvicorn app:app --reload                        # development
    uvicorn app:app --host 0.0.0.0 --port 8000      # production / Docker

Interactive API docs  (auto-generated by FastAPI)
-------------------------------------------------
    http://127.0.0.1:8000/docs      Swagger UI
    http://127.0.0.1:8000/redoc     ReDoc

Endpoints
---------
    GET  /                     Built-in HTML form / test UI
    GET  /api/health           Health check
    GET  /api/sections         Section metadata (titles, bounds, defaults)
    POST /api/generate/info    JSON preview — validates params, no file produced
    POST /api/generate/txt     Download TXT worksheet (Google Docs / Auto-LaTeX)
    POST /api/generate/pdf     Download print-ready PDF
    POST /api/generate/zip     Download ZIP with both TXT and PDF

PDF layout
----------
    • All problems left-justified: question number + prompt as plain text,
      math image flush to the left margin — no indentation column.
    • Page break between every version's questions and its answer key.
    • Answer key in a compact 4-column grid, designed to fit on one page.

Author : zekeg
Created: 12/02/2026
"""

import io
import zipfile
from typing import Dict, List, Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse, StreamingResponse
from pydantic import BaseModel, Field, field_validator, model_validator

import algebra2_radical_test as core


# ═══════════════════════════════════════════════════════════════
#  App instance
# ═══════════════════════════════════════════════════════════════

app = FastAPI(
    title="Algebra 2 Radical Test Generator",
    description=(
        "Generate randomized Algebra 2 worksheets covering radical simplification.\n\n"
        "**PDF layout:** problems are left-justified with a page break before each "
        "answer key. The answer key uses a compact 4-column grid to fit on one page.\n\n"
        "**TXT layout:** $$ ... $$ blocks rendered by Google Docs Auto-LaTeX add-on."
    ),
    version="2.1.0",
    contact={"name": "zekeg"},
    license_info={"name": "Copyright (c) zekeg 2026"},
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ═══════════════════════════════════════════════════════════════
#  Pydantic models
# ═══════════════════════════════════════════════════════════════

class SectionCounts(BaseModel):
    """
    Override the number of questions per section.
    Leave a field as null to use that section's default.
    """
    section_1: Optional[int] = Field(
        default=None, ge=1, le=30,
        description="Questions for Section 1 — Divide & Simplify (default 8)",
        examples=[8],
    )
    section_2: Optional[int] = Field(
        default=None, ge=1, le=20,
        description="Questions for Section 2 — Powers / Exponents (default 4)",
        examples=[4],
    )
    section_3: Optional[int] = Field(
        default=None, ge=1, le=20,
        description="Questions for Section 3 — Multiply Radicals (default 3)",
        examples=[3],
    )


class GenerateRequest(BaseModel):
    """
    All fields have sensible defaults — POST `{}` for a quick test worksheet.
    """
    test_title: str = Field(
        default="Algebra 2 Test: Simplifying Radicals",
        min_length=1, max_length=120,
        description="Title printed at the top of every version.",
        examples=["Period 3 — Radicals Quiz"],
    )
    num_versions: int = Field(
        default=5, ge=1, le=100,
        description="Number of unique randomized versions to generate.",
        examples=[33],
    )
    sections: List[int] = Field(
        default=[1, 2, 3],
        description="Sections to include — any non-empty subset of [1, 2, 3].",
        examples=[[1, 2, 3]],
    )
    section_counts: Optional[SectionCounts] = Field(
        default=None,
        description="Per-section question count overrides. Omit to use defaults.",
    )
    var_min: int = Field(
        default=1, ge=1, le=20,
        description="Minimum variable exponent (controls x^n, y^n, …).",
        examples=[1],
    )
    var_max: int = Field(
        default=10, ge=1, le=20,
        description="Maximum variable exponent.",
        examples=[10],
    )
    root_min: int = Field(
        default=2, ge=2, le=10,
        description="Minimum radical index  (2=√, 3=∛, 4=∜, …).",
        examples=[2],
    )
    root_max: int = Field(
        default=3, ge=2, le=10,
        description="Maximum radical index. Each problem picks randomly in [root_min, root_max].",
        examples=[3],
    )
    name_label: str = Field(
        default="Name", max_length=30,
        description="Label for the student name blank.",
        examples=["Nombre"],
    )
    date_label: str = Field(
        default="Date", max_length=30,
        description="Label for the date blank.",
        examples=["Fecha"],
    )
    period_label: str = Field(
        default="Period", max_length=30,
        description="Label for the period/class blank.",
        examples=["Periodo"],
    )

    @field_validator("sections")
    @classmethod
    def _validate_sections(cls, v):
        bad = [s for s in v if s not in {1, 2, 3}]
        if bad:
            raise ValueError(f"Invalid section number(s): {bad}. Must be 1, 2, or 3.")
        if not v:
            raise ValueError("At least one section must be selected.")
        return sorted(set(v))

    @model_validator(mode="after")
    def _validate_ranges(self):
        if self.var_min > self.var_max:
            raise ValueError("var_min must be ≤ var_max")
        if self.root_min > self.root_max:
            raise ValueError("root_min must be ≤ root_max")
        return self

    def resolved_counts(self) -> Dict[int, int]:
        """Merge user overrides with section defaults."""
        defaults = core.SECTION_Q_DEFAULTS
        if self.section_counts is None:
            return {s: defaults[s] for s in self.sections}
        overrides = {
            1: self.section_counts.section_1,
            2: self.section_counts.section_2,
            3: self.section_counts.section_3,
        }
        return {s: (overrides[s] if overrides[s] is not None else defaults[s])
                for s in self.sections}


# ═══════════════════════════════════════════════════════════════
#  Shared helpers
# ═══════════════════════════════════════════════════════════════

def _kwargs(req: GenerateRequest) -> dict:
    return dict(
        num_versions   = req.num_versions,
        test_title     = req.test_title,
        sections       = req.sections,
        section_counts = req.resolved_counts(),
        var_min        = req.var_min,
        var_max        = req.var_max,
        root_min       = req.root_min,
        root_max       = req.root_max,
        name_label     = req.name_label,
        date_label     = req.date_label,
        period_label   = req.period_label,
    )


def _safe_name(title: str) -> str:
    return (title.replace(" ", "_")
                 .replace(":", "")
                 .replace("/", "-")
                 .replace("\\", "-")[:60])


# ═══════════════════════════════════════════════════════════════
#  Routes
# ═══════════════════════════════════════════════════════════════

@app.get("/api/health", tags=["System"], summary="Health check")
def health():
    """Returns `{"status": "ok"}` when the service is running."""
    return {"status": "ok", "service": "Algebra 2 Radical Test Generator", "version": "2.1.0"}


@app.get("/api/sections", tags=["Metadata"], summary="List available sections")
def get_sections():
    """Titles, descriptions, default question counts, and min/max bounds for each section."""
    return {
        "sections": [
            {
                "section":           s,
                "title":             core.SECTION_TITLES[s],
                "description":       core.SECTION_DESCRIPTIONS[s],
                "default_questions": core.SECTION_Q_DEFAULTS[s],
                "min_questions":     core.SECTION_Q_BOUNDS[s][0],
                "max_questions":     core.SECTION_Q_BOUNDS[s][1],
            }
            for s in [1, 2, 3]
        ]
    }


@app.post("/api/generate/info", tags=["Generate"],
          summary="Preview generation settings (no file produced)")
def generate_info(req: GenerateRequest):
    """
    Validates all parameters and returns a JSON summary of what would be generated.
    Useful for confirming settings before requesting a download.
    """
    counts = req.resolved_counts()
    total  = sum(counts.values())
    return {
        "test_title":                  req.test_title,
        "num_versions":                req.num_versions,
        "sections":                    req.sections,
        "section_counts":              {str(k): v for k, v in counts.items()},
        "total_questions_per_version": total,
        "var_min":                     req.var_min,
        "var_max":                     req.var_max,
        "root_min":                    req.root_min,
        "root_max":                    req.root_max,
        "name_label":                  req.name_label,
        "date_label":                  req.date_label,
        "period_label":                req.period_label,
        "pdf_layout": {
            "problems":   "Left-justified — number + prompt as plain text, "
                          "math image flush to left margin",
            "answer_key": "Separate page per version, compact 4-column grid",
        },
        "note": (
            "POST to /api/generate/txt, /api/generate/pdf, or /api/generate/zip "
            "to download the worksheet."
        ),
    }


@app.post(
    "/api/generate/txt",
    tags=["Generate"],
    summary="Download worksheet as TXT (Google Docs / Auto-LaTeX)",
    responses={200: {"content": {"text/plain": {}}}},
)
def generate_txt(req: GenerateRequest):
    """
    Plain-text worksheet with all math in `$$ ... $$` blocks.

    To render equations in Google Docs:
    1. Paste the file into a Google Doc.
    2. **Extensions → Add-ons → Auto-LaTeX Equations → Start**
    """
    try:
        data = core.build_txt_bytes(**_kwargs(req))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    fname = f"{_safe_name(req.test_title)}_v{req.num_versions}.txt"
    return StreamingResponse(
        io.BytesIO(data),
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


@app.post(
    "/api/generate/pdf",
    tags=["Generate"],
    summary="Download print-ready PDF",
    responses={200: {"content": {"application/pdf": {}}}},
)
def generate_pdf(req: GenerateRequest):
    """
    Print-ready PDF worksheet.

    **Layout:**
    - Problems are **left-justified**: question number and prompt on one line,
      math image flush to the left margin — no indentation.
    - A **page break** separates every version's problems from its answer key.
    - The answer key uses a **compact 4-column grid** to fit on one page.

    ⚠️ Slower than TXT — each math expression is rendered as a PNG image.
    Allow 15–60 seconds for 33 versions.
    """
    try:
        data = core.build_pdf_bytes(**_kwargs(req))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    fname = f"{_safe_name(req.test_title)}_v{req.num_versions}.pdf"
    return StreamingResponse(
        io.BytesIO(data),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{fname}"'},
    )


@app.post(
    "/api/generate/zip",
    tags=["Generate"],
    summary="Download ZIP containing both TXT and PDF",
    responses={200: {"content": {"application/zip": {}}}},
)
def generate_zip(req: GenerateRequest):
    """
    Generates both formats and bundles them into a single ZIP archive.

    Contents:
    - `<title>_v<N>.txt` — Google Docs / Auto-LaTeX version
    - `<title>_v<N>.pdf` — print-ready PDF version
    """
    kw   = _kwargs(req)
    base = f"{_safe_name(req.test_title)}_v{req.num_versions}"
    try:
        txt_data = core.build_txt_bytes(**kw)
        pdf_data = core.build_pdf_bytes(**kw)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{base}.txt", txt_data)
        zf.writestr(f"{base}.pdf", pdf_data)
    zip_buf.seek(0)

    return StreamingResponse(
        zip_buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{base}.zip"'},
    )


# ═══════════════════════════════════════════════════════════════
#  Built-in HTML UI  (served at /)
# ═══════════════════════════════════════════════════════════════

@app.get("/", response_class=HTMLResponse, include_in_schema=False)
def root():
    return """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>Algebra 2 Radical Test Generator</title>
  <style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:system-ui,sans-serif;background:#f0f4f8;color:#1a202c}
    header{background:#2b6cb0;color:#fff;padding:1.4rem 2rem}
    header h1{font-size:1.5rem;font-weight:700}
    header p{font-size:.88rem;opacity:.85;margin-top:.3rem}
    main{max-width:880px;margin:1.8rem auto;padding:0 1rem}
    .card{background:#fff;border-radius:.75rem;padding:1.6rem;margin-bottom:1.4rem;
          box-shadow:0 1px 3px rgba(0,0,0,.1)}
    h2{font-size:1.05rem;font-weight:700;color:#2b6cb0;margin-bottom:.9rem;
       border-bottom:2px solid #ebf4ff;padding-bottom:.45rem}
    label{display:block;font-size:.83rem;font-weight:600;color:#4a5568;
          margin-top:.85rem;margin-bottom:.22rem}
    input,select{width:100%;padding:.48rem .65rem;border:1px solid #cbd5e0;
                 border-radius:.4rem;font-size:.93rem;background:#fff;color:#1a202c}
    input:focus,select:focus{outline:2px solid #4299e1;border-color:#4299e1}
    .row2{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
    .row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:.85rem}
    .sec-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.85rem;margin-top:.4rem}
    .sec-box{border:1px solid #e2e8f0;border-radius:.5rem;padding:.9rem}
    .sec-box label.title{font-size:.88rem;font-weight:700;color:#2d3748;
                         display:flex;align-items:center;gap:.4rem;margin:0 0 .3rem}
    .sec-box .desc{font-size:.78rem;color:#718096;margin-bottom:.5rem}
    input[type=checkbox]{width:auto}
    .note{font-size:.8rem;color:#718096;margin-top:.5rem;line-height:1.5}
    .btns{display:flex;gap:.7rem;flex-wrap:wrap;margin-top:1.2rem}
    button{padding:.62rem 1.4rem;border:none;border-radius:.5rem;font-size:.93rem;
           font-weight:700;cursor:pointer;transition:opacity .15s}
    .btn-info{background:#553c9a;color:#fff}
    .btn-txt {background:#2b6cb0;color:#fff}
    .btn-pdf {background:#276749;color:#fff}
    .btn-zip {background:#744210;color:#fff}
    button:hover{opacity:.85} button:disabled{opacity:.45;cursor:not-allowed}
    #status{margin-top:.9rem;padding:.7rem 1rem;border-radius:.4rem;
            font-size:.88rem;display:none;line-height:1.5}
    .info-bg{background:#ebf4ff;border:1px solid #90cdf4;color:#1a365d}
    .ok-bg  {background:#f0fff4;border:1px solid #9ae6b4;color:#1c4532}
    .err-bg {background:#fff5f5;border:1px solid #feb2b2;color:#742a2a}
    pre{background:#1a202c;color:#e2e8f0;padding:.9rem;border-radius:.45rem;
        overflow-x:auto;font-size:.78rem;margin-top:.65rem}
    .links{display:flex;gap:1.4rem;flex-wrap:wrap;align-items:center}
    .links a{color:#2b6cb0;font-weight:600;font-size:.88rem;text-decoration:none}
    .links a:hover{text-decoration:underline}
    footer{text-align:center;color:#718096;font-size:.78rem;padding:1.5rem}
  </style>
</head>
<body>
<header>
  <h1>📐 Algebra 2 Radical Test Generator</h1>
  <p>Randomized worksheets — left-justified PDF (answers on separate page) or Google Docs TXT</p>
</header>
<main>

  <div class="card">
    <div class="links">
      <a href="/docs"         target="_blank">📖 Swagger UI</a>
      <a href="/redoc"        target="_blank">📋 ReDoc</a>
      <a href="/api/sections" target="_blank">🔍 /api/sections</a>
      <a href="/api/health"   target="_blank">❤ /api/health</a>
    </div>
  </div>

  <div class="card">
    <h2>Configure Worksheet</h2>

    <label>Test Title</label>
    <input id="title" type="text" value="Algebra 2 Test: Simplifying Radicals" maxlength="120"/>

    <div class="row2">
      <div>
        <label>Number of Versions <span style="font-weight:400">(1–100)</span></label>
        <input id="nv" type="number" value="5" min="1" max="100"/>
      </div>
      <div></div>
    </div>

    <label>Sections &amp; Question Counts</label>
    <div class="sec-grid">
      <div class="sec-box">
        <label class="title">
          <input type="checkbox" id="s1" checked/>Section 1
        </label>
        <div class="desc">Divide &amp; Simplify</div>
        <label>Questions (1–30)</label>
        <input id="c1" type="number" value="8" min="1" max="30"/>
      </div>
      <div class="sec-box">
        <label class="title">
          <input type="checkbox" id="s2" checked/>Section 2
        </label>
        <div class="desc">Powers / Exponents</div>
        <label>Questions (1–20)</label>
        <input id="c2" type="number" value="4" min="1" max="20"/>
      </div>
      <div class="sec-box">
        <label class="title">
          <input type="checkbox" id="s3" checked/>Section 3
        </label>
        <div class="desc">Multiply Radicals</div>
        <label>Questions (1–20)</label>
        <input id="c3" type="number" value="3" min="1" max="20"/>
      </div>
    </div>

    <div class="row2">
      <div>
        <label>Root Index Min <span style="font-weight:400">(2=√  3=∛  4=∜ …)</span></label>
        <input id="rmin" type="number" value="2" min="2" max="10"/>
      </div>
      <div>
        <label>Root Index Max</label>
        <input id="rmax" type="number" value="3" min="2" max="10"/>
      </div>
    </div>

    <div class="row2">
      <div>
        <label>Variable Exponent Min</label>
        <input id="vmin" type="number" value="1" min="1" max="20"/>
      </div>
      <div>
        <label>Variable Exponent Max</label>
        <input id="vmax" type="number" value="10" min="1" max="20"/>
      </div>
    </div>

    <div class="row3">
      <div>
        <label>Name label</label>
        <input id="nl" type="text" value="Name" maxlength="30"/>
      </div>
      <div>
        <label>Date label</label>
        <input id="dl" type="text" value="Date" maxlength="30"/>
      </div>
      <div>
        <label>Period label</label>
        <input id="pl" type="text" value="Period" maxlength="30"/>
      </div>
    </div>

    <p class="note">
      📄 <b>PDF:</b> problems left-justified, answers on a separate page in a 4-column grid.<br>
      📝 <b>TXT:</b> paste into Google Docs → Extensions → Auto-LaTeX Equations → Start.
    </p>

    <div class="btns">
      <button class="btn-info" onclick="doInfo()">🔍 Preview (JSON)</button>
      <button class="btn-txt"  onclick="doGet('txt')">⬇ TXT</button>
      <button class="btn-pdf"  onclick="doGet('pdf')">⬇ PDF</button>
      <button class="btn-zip"  onclick="doGet('zip')">⬇ ZIP (both)</button>
    </div>

    <div id="status"></div>
  </div>

  <div id="preview_card" class="card" style="display:none">
    <h2>Preview</h2>
    <pre id="preview_pre"></pre>
  </div>

</main>
<footer>Algebra 2 Radical Test Generator v2.1 &bull; FastAPI + matplotlib + ReportLab</footer>

<script>
function payload(){
  const secs=[], sc={};
  [[1,'s1','c1'],[2,'s2','c2'],[3,'s3','c3']].forEach(([n,cb,ci])=>{
    if(document.getElementById(cb).checked){
      secs.push(n);
      sc['section_'+n]=parseInt(document.getElementById(ci).value)||null;
    }
  });
  return {
    test_title:     document.getElementById('title').value,
    num_versions:   parseInt(document.getElementById('nv').value),
    sections:       secs,
    section_counts: sc,
    root_min: parseInt(document.getElementById('rmin').value),
    root_max: parseInt(document.getElementById('rmax').value),
    var_min:  parseInt(document.getElementById('vmin').value),
    var_max:  parseInt(document.getElementById('vmax').value),
    name_label:   document.getElementById('nl').value,
    date_label:   document.getElementById('dl').value,
    period_label: document.getElementById('pl').value,
  };
}

function status(msg, type){
  const el=document.getElementById('status');
  el.className=type+'-bg'; el.textContent=msg; el.style.display='block';
}

async function doInfo(){
  status('Fetching preview…','info');
  try{
    const r=await fetch('/api/generate/info',{method:'POST',
      headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
    const j=await r.json();
    if(!r.ok){status('Error: '+(j.detail||r.statusText),'err');return;}
    document.getElementById('preview_pre').textContent=JSON.stringify(j,null,2);
    document.getElementById('preview_card').style.display='block';
    status('Preview ready.','ok');
  }catch(e){status('Network error: '+e.message,'err');}
}

async function doGet(fmt){
  const labels={txt:'TXT',pdf:'PDF',zip:'ZIP'};
  status(`Generating ${labels[fmt]}…  (PDF may take up to 60s for large batches)`,'info');
  const btns=document.querySelectorAll('button');
  btns.forEach(b=>b.disabled=true);
  try{
    const r=await fetch('/api/generate/'+fmt,{method:'POST',
      headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});
    if(!r.ok){
      const j=await r.json().catch(()=>({detail:r.statusText}));
      status('Error: '+(j.detail||r.statusText),'err'); return;
    }
    const blob=await r.blob();
    const cd=r.headers.get('Content-Disposition')||'';
    const m=cd.match(/filename="([^"]+)"/);
    const fname=m?m[1]:`worksheet.${fmt}`;
    const a=Object.assign(document.createElement('a'),
            {href:URL.createObjectURL(blob),download:fname});
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(a.href);
    status(`Downloaded: ${fname}`,'ok');
  }catch(e){status('Network error: '+e.message,'err');}
  finally{btns.forEach(b=>b.disabled=false);}
}
</script>
</body>
</html>"""
